spring.application.name=ResumeMatcher
#Ollama configuration 
spring.ai.ollamallama.base-url =https://localhost:11434
spring.ai.ollama.chat.model=llama3


#Save logs to file 
logging.file.name=app.log
#adjust levle globally or per package
logging.level.root=INFO
logging.level.com.example.ResumeMatcher=DEBUG

# Static resources configuration (add these)
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**